"""Convert HTML with inline styles to a Figma node tree.

This module parses HTML generated by the LLM and converts it into a JSON
structure that maps 1:1 to Figma's Plugin API, so the plugin renderer
can apply properties directly without interpretation.
"""

from __future__ import annotations

import logging
import re
from html.parser import HTMLParser
from typing import Any

logger = logging.getLogger(__name__)

# ─── CSS Parsing Helpers ───


def _parse_inline_style(style_str: str) -> dict[str, str]:
    """Parse inline CSS like 'display: flex; color: #fff' into a dict."""
    props: dict[str, str] = {}
    if not style_str:
        return props
    for part in style_str.split(";"):
        part = part.strip()
        if ":" not in part:
            continue
        key, value = part.split(":", 1)
        props[key.strip().lower()] = value.strip()
    return props


def _parse_hex_color(hex_str: str) -> dict[str, float] | None:
    """Parse #RGB, #RRGGBB to {r, g, b} in 0-1 range."""
    h = hex_str.strip().lstrip("#")
    if len(h) == 3:
        h = h[0] * 2 + h[1] * 2 + h[2] * 2
    if len(h) != 6:
        return None
    try:
        return {
            "r": int(h[0:2], 16) / 255,
            "g": int(h[2:4], 16) / 255,
            "b": int(h[4:6], 16) / 255,
        }
    except ValueError:
        return None


def _parse_color(color_str: str) -> dict[str, float] | None:
    """Parse CSS color value to {r, g, b} (0-1 range)."""
    color_str = color_str.strip()
    if color_str.startswith("#"):
        return _parse_hex_color(color_str)

    # rgb(R, G, B) or rgba(R, G, B, A)
    m = re.match(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)", color_str)
    if m:
        return {
            "r": int(m.group(1)) / 255,
            "g": int(m.group(2)) / 255,
            "b": int(m.group(3)) / 255,
        }

    # Named colors (common subset)
    named = {
        "white": {"r": 1.0, "g": 1.0, "b": 1.0},
        "black": {"r": 0.0, "g": 0.0, "b": 0.0},
        "transparent": None,
        "red": {"r": 1.0, "g": 0.0, "b": 0.0},
        "green": {"r": 0.0, "g": 0.5, "b": 0.0},
        "blue": {"r": 0.0, "g": 0.0, "b": 1.0},
    }
    return named.get(color_str.lower())


def _parse_color_with_opacity(color_str: str) -> tuple[dict[str, float] | None, float]:
    """Parse color + extract opacity from rgba()."""
    color_str = color_str.strip()
    m = re.match(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)", color_str)
    if m:
        color = {
            "r": int(m.group(1)) / 255,
            "g": int(m.group(2)) / 255,
            "b": int(m.group(3)) / 255,
        }
        return color, float(m.group(4))
    return _parse_color(color_str), 1.0


def _parse_px(value: str) -> float | None:
    """Parse '16px' or '16' to float. Ignores em/rem/% units."""
    value = value.strip().lower()
    if value.endswith("%") or value.endswith("em") or value.endswith("rem"):
        return None
    value = value.replace("px", "")
    try:
        return float(value)
    except ValueError:
        return None


def _parse_letter_spacing(value: str, font_size: float) -> float | None:
    """Parse letter-spacing, supporting px and em units."""
    value = value.strip().lower()
    if value.endswith("em"):
        try:
            return float(value.replace("em", "")) * font_size
        except ValueError:
            return None
    return _parse_px(value)


def _parse_padding(value: str) -> tuple[float, float, float, float]:
    """Parse CSS padding shorthand to (top, right, bottom, left)."""
    parts = value.strip().split()
    nums = []
    for p in parts:
        n = _parse_px(p)
        nums.append(n if n is not None else 0)

    if len(nums) == 1:
        return (nums[0], nums[0], nums[0], nums[0])
    if len(nums) == 2:
        return (nums[0], nums[1], nums[0], nums[1])
    if len(nums) == 3:
        return (nums[0], nums[1], nums[2], nums[1])
    if len(nums) >= 4:
        return (nums[0], nums[1], nums[2], nums[3])
    return (0, 0, 0, 0)


def _parse_border(value: str) -> tuple[float, dict[str, float] | None]:
    """Parse 'Npx solid #color' to (weight, color)."""
    parts = value.strip().split()
    weight = 1.0
    color = None
    for part in parts:
        px = _parse_px(part)
        if px is not None:
            weight = px
        elif part.startswith("#") or part.startswith("rgb"):
            color = _parse_color(part)
        elif part in ("solid", "dashed", "dotted", "none") and part == "none":
            return (0, None)
    return (weight, color)


def _parse_box_shadow(value: str) -> dict[str, Any] | None:
    """Parse CSS box-shadow to Figma DROP_SHADOW effect."""
    # Match: offsetX offsetY blur [spread] color
    m = re.match(
        r"([\d.-]+)(?:px)?\s+([\d.-]+)(?:px)?\s+([\d.-]+)(?:px)?\s*(?:([\d.-]+)(?:px)?\s+)?"
        r"(rgba?\([^)]+\)|#[0-9a-fA-F]{3,8})",
        value.strip(),
    )
    if not m:
        return None

    offset_x = float(m.group(1))
    offset_y = float(m.group(2))
    blur = float(m.group(3))
    color_str = m.group(5)

    color_rgb, alpha = _parse_color_with_opacity(color_str)
    if not color_rgb:
        return None

    return {
        "type": "DROP_SHADOW",
        "color": {"r": color_rgb["r"], "g": color_rgb["g"], "b": color_rgb["b"], "a": alpha},
        "offset": {"x": offset_x, "y": offset_y},
        "radius": blur,
        "spread": 0,
        "visible": True,
        "blendMode": "NORMAL",
    }


def _parse_border_radius(value: str) -> float:
    """Parse border-radius value. Handles '12px', '50%', '9999px'."""
    value = value.strip()
    if value.endswith("%"):
        # 50% typically means circle — use a large number
        try:
            pct = float(value.replace("%", ""))
            return 9999 if pct >= 50 else pct
        except ValueError:
            return 0
    px = _parse_px(value)
    return px if px is not None else 0


def _font_weight_to_style(weight: int) -> str:
    """Convert CSS font-weight number to Figma font style name."""
    if weight >= 700:
        return "Bold"
    if weight >= 600:
        return "Semi Bold"
    if weight >= 500:
        return "Medium"
    return "Regular"


# ─── HTML Parser ───

# Tags that should become TEXT nodes (when they only contain text)
TEXT_TAGS = {
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "span",
    "label",
    "a",
    "strong",
    "em",
    "b",
    "i",
    "small",
}

# Tags to skip entirely
SKIP_TAGS = {"script", "style", "link", "meta", "head", "html", "body", "br", "hr"}

# Recognized Lucide icon names (keep in sync with figma-plugin/src/icons.ts)
ICON_NAMES = {
    "home", "menu", "x", "chevron-down", "chevron-right", "chevron-left",
    "chevron-up", "arrow-left", "arrow-right", "arrow-up", "arrow-down",
    "external-link", "log-out", "log-in", "search", "plus", "minus", "edit",
    "trash", "copy", "filter", "more-horizontal", "more-vertical", "download",
    "upload", "refresh", "user", "users", "shield", "lock", "key", "bell",
    "mail", "message-square", "phone", "globe", "bar-chart", "line-chart",
    "pie-chart", "trending-up", "trending-down", "activity", "zap", "target",
    "dollar-sign", "credit-card", "shopping-cart", "shopping-bag", "package",
    "wallet", "receipt", "file", "file-text", "folder", "image", "paperclip",
    "link", "check", "check-circle", "alert-circle", "alert-triangle", "info",
    "x-circle", "settings", "eye", "eye-off", "bookmark", "star", "heart",
    "calendar", "clock", "map-pin", "layers", "layout", "grid", "sliders",
    "inbox", "cloud", "database", "help-circle", "share", "printer",
    "circle-dot", "rocket", "sparkles",
}

# Void (self-closing) tags
VOID_TAGS = {"br", "hr", "img", "input", "meta", "link"}


class _HTMLToTreeParser(HTMLParser):
    """Parse HTML into a nested dict structure."""

    def __init__(self) -> None:
        super().__init__()
        self.root: dict[str, Any] | None = None
        self.stack: list[dict[str, Any]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() in SKIP_TAGS:
            return

        attr_dict = {k: v or "" for k, v in attrs}
        node: dict[str, Any] = {
            "tag": tag.lower(),
            "attrs": attr_dict,
            "style": _parse_inline_style(attr_dict.get("style", "")),
            "children": [],
            "text": "",
        }

        if self.stack:
            self.stack[-1]["children"].append(node)
        elif self.root is None:
            self.root = node

        if tag.lower() not in VOID_TAGS:
            self.stack.append(node)

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() in SKIP_TAGS or tag.lower() in VOID_TAGS:
            return
        if self.stack and self.stack[-1]["tag"] == tag.lower():
            self.stack.pop()

    def handle_data(self, data: str) -> None:
        text = data.strip()
        if not text:
            return
        if self.stack:
            current = self.stack[-1]
            if current["text"]:
                current["text"] += " " + text
            else:
                current["text"] = text


def _parse_html(html: str) -> dict[str, Any] | None:
    """Parse HTML string into a nested dict tree."""
    parser = _HTMLToTreeParser()
    parser.feed(html)
    return parser.root


# ─── HTML Tree → Figma Tree Conversion ───


def _is_text_only(node: dict[str, Any]) -> bool:
    """Check if a node contains only text (no child elements)."""
    return len(node.get("children", [])) == 0 and bool(node.get("text", "").strip())


def _apply_text_transform(text: str, transform: str) -> str:
    """Apply CSS text-transform to text content."""
    transform = transform.strip().lower()
    if transform == "uppercase":
        return text.upper()
    if transform == "lowercase":
        return text.lower()
    if transform == "capitalize":
        return text.title()
    return text


def _convert_text_node(node: dict[str, Any]) -> dict[str, Any]:
    """Convert a text-only HTML element to a Figma TEXT node."""
    style = node.get("style", {})
    tag = node.get("tag", "span")

    # Determine font properties from tag and style
    default_sizes = {
        "h1": 48,
        "h2": 32,
        "h3": 24,
        "h4": 20,
        "h5": 16,
        "h6": 14,
        "p": 16,
        "span": 16,
        "label": 14,
        "small": 12,
        "a": 16,
    }
    default_weights = {
        "h1": 700,
        "h2": 700,
        "h3": 600,
        "h4": 600,
        "h5": 600,
        "h6": 600,
        "strong": 700,
        "b": 700,
        "p": 400,
        "span": 400,
        "label": 500,
        "small": 400,
        "a": 500,
    }

    font_size = _parse_px(style.get("font-size", "")) or default_sizes.get(tag, 16)
    raw_weight = style.get("font-weight", "")
    try:
        font_weight = int(raw_weight) if raw_weight else default_weights.get(tag, 400)
    except ValueError:
        weight_map = {"bold": 700, "semibold": 600, "medium": 500, "normal": 400, "light": 300}
        font_weight = weight_map.get(raw_weight.lower(), 400)

    line_height_str = style.get("line-height", "")
    line_height = _parse_px(line_height_str)
    if line_height is None:
        line_height = round(font_size * 1.4)

    text_color = _parse_color(style.get("color", "#0F172A")) or {"r": 0.06, "g": 0.09, "b": 0.16}

    text_align = style.get("text-align", "left").upper()
    if text_align not in ("LEFT", "CENTER", "RIGHT"):
        text_align = "LEFT"

    # Apply text-transform
    characters = node.get("text", "")
    text_transform = style.get("text-transform", "")
    if text_transform:
        characters = _apply_text_transform(characters, text_transform)

    result: dict[str, Any] = {
        "type": "TEXT",
        "characters": characters,
        "fontSize": font_size,
        "fontWeight": font_weight,
        "lineHeight": line_height,
        "textColor": text_color,
        "textAlignHorizontal": text_align,
    }

    # Letter spacing (supports px and em)
    ls = style.get("letter-spacing", "")
    ls_px = _parse_letter_spacing(ls, font_size)
    if ls_px is not None:
        result["letterSpacing"] = ls_px

    # Text decoration (underline, strikethrough)
    td = style.get("text-decoration", "").strip().lower()
    if "underline" in td:
        result["textDecoration"] = "UNDERLINE"
    elif "line-through" in td:
        result["textDecoration"] = "STRIKETHROUGH"

    # Layout properties for text in auto-layout parents (flex → layoutGrow)
    flex = style.get("flex", "").strip()
    flex_grow_val = style.get("flex-grow", "").strip()
    if flex:
        try:
            if float(flex.split()[0]) >= 1:
                result["layoutGrow"] = 1
        except ValueError:
            pass
    elif flex_grow_val:
        try:
            if float(flex_grow_val) >= 1:
                result["layoutGrow"] = 1
        except ValueError:
            pass

    if style.get("width", "") == "100%":
        result["layoutAlign"] = "STRETCH"

    # textAutoResize:
    # - WIDTH_AND_HEIGHT: text shrink-wraps to content (default for most text)
    # - HEIGHT: text width is externally controlled (stretch/grow)
    if result.get("layoutGrow") == 1 or result.get("layoutAlign") == "STRETCH":
        result["textAutoResize"] = "HEIGHT"
    else:
        result["textAutoResize"] = "WIDTH_AND_HEIGHT"

    return result


def _split_shadow(value: str) -> list[str]:
    """Split multiple box-shadow values on commas outside parentheses."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in value:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(ch)
    parts.append("".join(current))
    return parts


def _resolve_sizing_modes(result: dict[str, Any]) -> None:
    """Resolve primaryAxisSizingMode and counterAxisSizingMode based on all signals.

    Called ONCE at the end of _convert_frame_node(), after children conversion
    and defensive heuristics. Centralizes all sizing logic.

    Rules:
    - Explicit dimension on an axis → FIXED (Figma ignores resize() with AUTO/HUG)
    - Children with layoutGrow on primary axis → parent must be FIXED
    - layoutGrow on the frame itself → counter axis FIXED if it has explicit dimension
    - Otherwise → AUTO (hug contents)
    """
    layout = result.get("layoutMode", "VERTICAL")
    children = result.get("children", [])
    has_grow_children = any(c.get("layoutGrow") == 1 for c in children)

    if layout == "VERTICAL":
        # Primary axis = height, Counter axis = width
        if "height" in result or has_grow_children:
            result["primaryAxisSizingMode"] = "FIXED"
        else:
            result.setdefault("primaryAxisSizingMode", "AUTO")

        if "width" in result:
            result["counterAxisSizingMode"] = "FIXED"
        else:
            result.setdefault("counterAxisSizingMode", "AUTO")

    elif layout == "HORIZONTAL":
        # Primary axis = width, Counter axis = height
        if "width" in result or has_grow_children:
            result["primaryAxisSizingMode"] = "FIXED"
        else:
            result.setdefault("primaryAxisSizingMode", "AUTO")

        if "height" in result:
            result["counterAxisSizingMode"] = "FIXED"
        else:
            result.setdefault("counterAxisSizingMode", "AUTO")

    # When frame itself fills parent (layoutGrow), fix counter axis if explicit dim
    if result.get("layoutGrow") == 1 and (
        (layout == "VERTICAL" and "width" in result)
        or (layout == "HORIZONTAL" and "height" in result)
    ):
        result["counterAxisSizingMode"] = "FIXED"


def _convert_frame_node(node: dict[str, Any]) -> dict[str, Any]:
    """Convert an HTML element to a Figma FRAME node."""
    style = node.get("style", {})
    tag = node.get("tag", "div")

    result: dict[str, Any] = {
        "type": "FRAME",
        "name": node.get("attrs", {}).get("data-name", tag),
        "children": [],
    }

    # ─── Layout ───
    display = style.get("display", "")
    flex_dir = style.get(
        "flex-direction",
        "column"
        if tag in ("div", "section", "main", "form", "nav", "header", "footer", "article", "aside")
        else "row",
    )

    if "flex" in display or "grid" in display:
        result["layoutMode"] = "HORIZONTAL" if flex_dir == "row" else "VERTICAL"
    else:
        # Default: vertical layout for block elements
        result["layoutMode"] = "VERTICAL"

    # Gap / itemSpacing
    gap = _parse_px(style.get("gap", ""))
    if gap is not None:
        result["itemSpacing"] = gap
    else:
        result["itemSpacing"] = 0

    # Alignment
    align_items = style.get("align-items", "").lower()
    align_map = {
        "center": "CENTER",
        "flex-start": "MIN",
        "start": "MIN",
        "flex-end": "MAX",
        "end": "MAX",
        "stretch": "MIN",
    }
    if align_items in align_map:
        result["counterAxisAlignItems"] = align_map[align_items]

    justify = style.get("justify-content", "").lower()
    justify_map = {
        "center": "CENTER",
        "flex-start": "MIN",
        "start": "MIN",
        "flex-end": "MAX",
        "end": "MAX",
        "space-between": "SPACE_BETWEEN",
    }
    if justify in justify_map:
        result["primaryAxisAlignItems"] = justify_map[justify]

    # ─── Size ───
    width = style.get("width", "")
    height = style.get("height", "")
    min_width = style.get("min-width", "")
    max_width = style.get("max-width", "")
    min_height = style.get("min-height", "")

    w_px = _parse_px(width)
    h_px = _parse_px(height)

    if w_px is not None:
        result["width"] = w_px
    if h_px is not None:
        result["height"] = h_px

    # min-width/height as fallback dimensions
    if w_px is None and min_width:
        mw = _parse_px(min_width)
        if mw is not None:
            result["width"] = mw

    if h_px is None and min_height:
        mh = _parse_px(min_height)
        if mh is not None:
            result["height"] = mh

    # flex shorthand or flex-grow → layoutGrow
    # Handles: flex: 1, flex: 1 1 0%, flex: 1 0 auto, flex: 2, flex-grow: 1
    flex = style.get("flex", "").strip()
    flex_grow = style.get("flex-grow", "").strip()
    if flex:
        flex_parts = flex.split()
        try:
            grow_val = float(flex_parts[0])
            if grow_val >= 1:
                result["layoutGrow"] = 1
        except ValueError:
            pass
    elif flex_grow:
        try:
            if float(flex_grow) >= 1:
                result["layoutGrow"] = 1
        except ValueError:
            pass

    # width: 100% → layoutAlign STRETCH
    if width == "100%" or max_width == "100%":
        result["layoutAlign"] = "STRETCH"

    # ─── Padding ───
    padding = style.get("padding", "")
    if padding:
        pt, pr, pb, pl = _parse_padding(padding)
        result["paddingTop"] = pt
        result["paddingRight"] = pr
        result["paddingBottom"] = pb
        result["paddingLeft"] = pl

    # Individual padding overrides
    for side, key in [
        ("top", "paddingTop"),
        ("right", "paddingRight"),
        ("bottom", "paddingBottom"),
        ("left", "paddingLeft"),
    ]:
        val = style.get(f"padding-{side}", "")
        px = _parse_px(val)
        if px is not None:
            result[key] = px

    # ─── Background ───
    bg_color_str = style.get("background-color", "") or style.get("background", "")
    if (
        bg_color_str
        and not bg_color_str.startswith("linear-gradient")
        and not bg_color_str.startswith("url")
    ):
        bg_color, bg_opacity = _parse_color_with_opacity(bg_color_str)
        if bg_color:
            fill: dict[str, Any] = {"type": "SOLID", "color": bg_color}
            if bg_opacity < 1:
                fill["opacity"] = bg_opacity
            result["fills"] = [fill]

    # Linear gradient fallback: extract first color
    if bg_color_str.startswith("linear-gradient"):
        colors = re.findall(r"#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)", bg_color_str)
        if colors:
            first_color = _parse_color(colors[0])
            if first_color:
                result["fills"] = [{"type": "SOLID", "color": first_color}]

    # ─── Border ───
    border_str = style.get("border", "")
    if border_str and "none" not in border_str:
        weight, color = _parse_border(border_str)
        if color and weight > 0:
            result["strokes"] = [{"type": "SOLID", "color": color}]
            result["strokeWeight"] = weight
            result["strokeAlign"] = "INSIDE"

    # Individual border sides (border-bottom, etc.)
    for side in ("top", "right", "bottom", "left"):
        side_border = style.get(f"border-{side}", "")
        if side_border and "none" not in side_border:
            weight, color = _parse_border(side_border)
            if color and weight > 0 and "strokes" not in result:
                result["strokes"] = [{"type": "SOLID", "color": color}]
                result["strokeWeight"] = weight
                result["strokeAlign"] = "INSIDE"

    # ─── Border Radius ───
    radius_str = style.get("border-radius", "")
    if radius_str:
        result["cornerRadius"] = _parse_border_radius(radius_str)

    # ─── Shadow ───
    shadow_str = style.get("box-shadow", "")
    if shadow_str and shadow_str != "none":
        # Handle multiple shadows — split on commas outside parens, take first
        first_shadow = _split_shadow(shadow_str)[0].strip()
        effect = _parse_box_shadow(first_shadow)
        if effect:
            result["effects"] = [effect]

    # ─── Overflow ───
    overflow = style.get("overflow", "")
    if overflow == "hidden" or overflow == "auto" or overflow == "scroll":
        result["clipsContent"] = True

    # ─── Opacity ───
    opacity_str = style.get("opacity", "")
    if opacity_str:
        import contextlib

        with contextlib.suppress(ValueError):
            result["opacity"] = float(opacity_str)

    # ─── Convert children ───
    for child in node.get("children", []):
        figma_child = _convert_node(child)
        if figma_child:
            result["children"].append(figma_child)

    # ─── CSS default: align-items: stretch ───
    # In CSS flex, children stretch in the cross-axis by default.
    # In Figma, this must be explicit via layoutAlign = "STRETCH".
    # Only skip if parent explicitly sets align-items to non-stretch.
    parent_align = align_items  # from earlier parsing
    should_stretch = parent_align in ("", "stretch")
    if should_stretch:
        for child_node in result["children"]:
            # Buttons should NOT stretch by default (they hug content)
            if "layoutAlign" not in child_node and child_node.get("name") != "button":
                child_node["layoutAlign"] = "STRETCH"
            # TEXT nodes with STRETCH need textAutoResize="HEIGHT"
            # (STRETCH applied here after _convert_text_node returned)
            if (
                child_node.get("type") == "TEXT"
                and child_node.get("layoutAlign") == "STRETCH"
            ):
                child_node["textAutoResize"] = "HEIGHT"

    # ─── Defensive heuristic: TEXT siblings in HORIZONTAL → layoutGrow ───
    # When a HORIZONTAL parent has 2+ TEXT children without layoutGrow,
    # they are likely table cells — give them all layoutGrow=1.
    if result["layoutMode"] == "HORIZONTAL":
        text_children_no_grow = [
            c for c in result["children"]
            if c.get("type") == "TEXT" and c.get("layoutGrow") != 1
        ]
        if len(text_children_no_grow) >= 2:
            for c in text_children_no_grow:
                c["layoutGrow"] = 1
                c["textAutoResize"] = "HEIGHT"
            logger.info(
                "Defensive: layoutGrow=1 on %d TEXT children in HORIZONTAL '%s'",
                len(text_children_no_grow),
                result.get("name", "?"),
            )

    # ─── Defensive heuristic: FRAME children in HORIZONTAL without width ───
    # Frames in a HORIZONTAL parent without flex:1 or explicit width collapse
    # to width=0, causing vertical text wrapping.
    # Only applies when 2+ children exist (distribution makes no sense with 1 child).
    # Excludes buttons and centered frames (badges, icons) which should hug content.
    if result["layoutMode"] == "HORIZONTAL" and len(result["children"]) >= 2:
        children_needing_grow = [
            c for c in result["children"]
            if c.get("type") == "FRAME"
            and "width" not in c
            and c.get("layoutGrow") != 1
            and c.get("name") != "button"
            and c.get("primaryAxisAlignItems") != "CENTER"
            and len(c.get("children", [])) > 0
        ]
        if children_needing_grow:
            for c in children_needing_grow:
                c["layoutGrow"] = 1
            logger.info(
                "Defensive: layoutGrow=1 on %d FRAME children in HORIZONTAL '%s'",
                len(children_needing_grow),
                result.get("name", "?"),
            )

    # ─── Inject text content as child TEXT node ───
    # Handles both: (a) frame with text AND children, (b) text-only frame (e.g. <div>text</div>)
    text = node.get("text", "").strip()
    if text:
        # Apply text-transform if present
        text_transform = style.get("text-transform", "")
        if text_transform:
            text = _apply_text_transform(text, text_transform)

        font_size = _parse_px(style.get("font-size", "")) or 16
        raw_weight = style.get("font-weight", "")
        try:
            font_weight = int(raw_weight) if raw_weight else 400
        except ValueError:
            weight_map = {"bold": 700, "semibold": 600, "medium": 500, "normal": 400}
            font_weight = weight_map.get(raw_weight.lower(), 400)

        text_node: dict[str, Any] = {
            "type": "TEXT",
            "characters": text,
            "fontSize": font_size,
            "fontWeight": font_weight,
            "lineHeight": round(font_size * 1.4),
            "textColor": _parse_color(style.get("color", "#0F172A"))
            or {"r": 0.06, "g": 0.09, "b": 0.16},
            "textAlignHorizontal": "LEFT",
        }
        if should_stretch:
            text_node["layoutAlign"] = "STRETCH"
            text_node["textAutoResize"] = "HEIGHT"
        else:
            text_node["textAutoResize"] = "WIDTH_AND_HEIGHT"
        result["children"].insert(0, text_node)

    # ─── Resolve sizing modes (centralized logic) ───
    _resolve_sizing_modes(result)

    return result


def _convert_input_node(node: dict[str, Any]) -> dict[str, Any]:
    """Convert an <input> element to a Figma FRAME with placeholder text."""
    style = node.get("style", {})
    attrs = node.get("attrs", {})

    placeholder = attrs.get("placeholder", "Enter text...")
    input_type = attrs.get("type", "text")

    frame = _convert_frame_node(
        {
            "tag": "div",
            "attrs": {},
            "style": {**style, "display": "flex", "flex-direction": "row"},
            "children": [],
            "text": "",
        }
    )

    frame["name"] = f"input_{input_type}"

    # Default input styling if not in style
    if "paddingTop" not in frame:
        frame["paddingTop"] = 10
        frame["paddingRight"] = 12
        frame["paddingBottom"] = 10
        frame["paddingLeft"] = 12

    if "cornerRadius" not in frame:
        frame["cornerRadius"] = 8

    if "fills" not in frame:
        frame["fills"] = [{"type": "SOLID", "color": {"r": 1.0, "g": 1.0, "b": 1.0}}]

    if "strokes" not in frame:
        frame["strokes"] = [{"type": "SOLID", "color": {"r": 0.89, "g": 0.91, "b": 0.94}}]
        frame["strokeWeight"] = 1
        frame["strokeAlign"] = "INSIDE"

    # Placeholder text
    frame["children"] = [
        {
            "type": "TEXT",
            "characters": placeholder,
            "fontSize": _parse_px(style.get("font-size", "")) or 14,
            "fontWeight": 400,
            "lineHeight": 20,
            "textColor": {"r": 0.58, "g": 0.64, "b": 0.72},  # text-muted
            "textAlignHorizontal": "LEFT",
        }
    ]

    # Set explicit height if provided, else default
    h = _parse_px(style.get("height", ""))
    if h:
        frame["height"] = h
    else:
        frame["height"] = 44

    frame["counterAxisSizingMode"] = "FIXED"
    frame["counterAxisAlignItems"] = "CENTER"

    return frame


def _convert_icon_node(node: dict[str, Any]) -> dict[str, Any]:
    """Convert an element with data-icon to an ICON node."""
    attrs = node.get("attrs", {})
    style = node.get("style", {})
    icon_name = attrs.get("data-icon", "")

    # Size from CSS width/height, default 24
    size_w = _parse_px(style.get("width", "")) or 24
    size_h = _parse_px(style.get("height", "")) or 24

    # Color from CSS color property
    color_str = style.get("color", "#64748B")
    color = _parse_color(color_str) or {"r": 0.39, "g": 0.45, "b": 0.53}

    return {
        "type": "ICON",
        "name": f"icon_{icon_name}",
        "icon": icon_name,
        "width": size_w,
        "height": size_h,
        "color": color,
    }


def _convert_node(node: dict[str, Any]) -> dict[str, Any] | None:
    """Convert any HTML element to a Figma node."""
    tag = node.get("tag", "div")

    if tag in SKIP_TAGS:
        return None

    # display: none → skip this element entirely
    style = node.get("style", {})
    if style.get("display", "").strip().lower() == "none":
        return None

    # data-icon → ICON node (Lucide SVG icon)
    attrs = node.get("attrs", {})
    icon_name = attrs.get("data-icon", "")
    if icon_name and icon_name in ICON_NAMES:
        return _convert_icon_node(node)

    # <input> → special handling
    if tag == "input":
        return _convert_input_node(node)

    # <button> → FRAME with text
    if tag == "button":
        return _convert_button_node(node)

    # Text-only elements → TEXT node
    if tag in TEXT_TAGS and _is_text_only(node):
        return _convert_text_node(node)

    # Elements with children or mixed content → FRAME
    return _convert_frame_node(node)


def _convert_button_node(node: dict[str, Any]) -> dict[str, Any]:
    """Convert a <button> element to a Figma FRAME with label text."""
    style = node.get("style", {})

    frame = _convert_frame_node(
        {
            "tag": "div",
            "attrs": {},
            "style": {**style, "display": "flex", "flex-direction": "row"},
            "children": node.get("children", []),
            "text": "",
        }
    )

    frame["name"] = "button"
    frame["layoutMode"] = "HORIZONTAL"

    # Default button styling
    if "paddingTop" not in frame:
        frame["paddingTop"] = 10
        frame["paddingRight"] = 20
        frame["paddingBottom"] = 10
        frame["paddingLeft"] = 20

    if "cornerRadius" not in frame:
        frame["cornerRadius"] = 8

    if "counterAxisAlignItems" not in frame:
        frame["counterAxisAlignItems"] = "CENTER"
    if "primaryAxisAlignItems" not in frame:
        frame["primaryAxisAlignItems"] = "CENTER"

    # Button label text
    label = node.get("text", "").strip()
    if label:
        text_color = _parse_color(style.get("color", "#FFFFFF")) or {"r": 1, "g": 1, "b": 1}
        font_size = _parse_px(style.get("font-size", "")) or 14
        font_weight_str = style.get("font-weight", "600")
        try:
            fw = int(font_weight_str)
        except ValueError:
            fw = 600

        frame["children"].insert(
            0,
            {
                "type": "TEXT",
                "characters": label,
                "fontSize": font_size,
                "fontWeight": fw,
                "lineHeight": round(font_size * 1.4),
                "textColor": text_color,
                "textAlignHorizontal": "CENTER",
            },
        )

    return frame


# ─── Tree Validation ───


def _validate_tree(tree: dict[str, Any], path: str = "root") -> list[str]:
    """Validate a Figma node tree and return warnings for suspicious patterns."""
    warnings: list[str] = []
    node_type = tree.get("type", "FRAME")

    # ICON and TEXT are leaf nodes — no children to validate
    if node_type in ("ICON", "TEXT"):
        return warnings

    if node_type == "FRAME":
        if not tree.get("children"):
            warnings.append(f"{path}: FRAME with no children")

        if tree.get("layoutGrow") == 1 and tree.get("primaryAxisSizingMode") == "AUTO":
            warnings.append(f"{path}: has layoutGrow=1 but parent might be AUTO (check parent)")

        for i, child in enumerate(tree.get("children", [])):
            child_name = child.get("name", child.get("characters", f"child_{i}"))
            child_path = f"{path}/{child_name}"

            if child.get("type") == "TEXT":
                has_grow = child.get("layoutGrow") == 1
                has_stretch = child.get("layoutAlign") == "STRETCH"
                if (has_grow or has_stretch) and "textAutoResize" not in child:
                    warnings.append(
                        f"{child_path}: TEXT with layoutGrow/STRETCH but no textAutoResize"
                    )

            warnings.extend(_validate_tree(child, child_path))

    return warnings


# ─── Public API ───


def convert_html_to_figma_tree(html: str, screen_name: str) -> dict[str, Any]:
    """Convert an HTML string to a Figma node tree.

    Args:
        html: Complete HTML string with inline styles.
        screen_name: Name for the root frame.

    Returns:
        A dict representing the Figma node tree, ready for the plugin renderer.
    """
    root = _parse_html(html)
    if not root:
        # Return a minimal empty frame
        return {
            "type": "FRAME",
            "name": screen_name,
            "layoutMode": "VERTICAL",
            "primaryAxisSizingMode": "AUTO",
            "counterAxisSizingMode": "FIXED",
            "width": 1440,
            "height": 900,
            "fills": [{"type": "SOLID", "color": {"r": 1, "g": 1, "b": 1}}],
            "children": [],
        }

    tree = _convert_node(root)
    if tree is None:
        tree = {"type": "FRAME", "name": screen_name, "children": []}

    # Ensure root frame properties
    tree["name"] = screen_name
    if "width" not in tree:
        tree["width"] = 1440
    tree["type"] = "FRAME"

    # Root frame: fixed height to prevent unbounded growth
    if "height" not in tree:
        tree["height"] = 900
    tree["primaryAxisSizingMode"] = "FIXED"
    tree["clipsContent"] = True

    logger.info(
        "Converted screen '%s': %dx%d, %d children",
        screen_name,
        tree.get("width", 0),
        tree.get("height", 0),
        len(tree.get("children", [])),
    )

    # Post-conversion validation: log warnings for suspicious patterns
    warnings = _validate_tree(tree)
    for w in warnings:
        logger.warning("Tree validation: %s", w)

    return tree
